[project]
name = "little"
version = "0.1.10"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aswin402", email = "aswinvishal402@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "sympy>=1.14.0",
]

[project.scripts]
little = "little.main:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
